
-----CREACION DE USUARIO----
CREATE USER PROYECTO_ADMIN IDENTIFIED BY 123;
GRANT DBA TO PROYECTO_ADMIN;
GRANT CREATE SESSION TO PROYECTO_ADMIN;

--- TABLA TELEFONO--
CREATE TABLE FIDE_TELEFONO_TB(
TELEFONO_ID NUMBER CONSTRAINT FIDE_TELEFONO_TB_PK PRIMARY KEY,
NUMERO NUMBER CONSTRAINT FIDE_TELEFONO_TB_NOT_NULL NOT NULL,
TIPO VARCHAR2(100),
EXT VARCHAR2(100)
);
--- PROVEEDOR---
CREATE TABLE FIDE_PROVEEDOR_TB (
PROVEEDOR_ID NUMBER CONSTRAINT FIDE_PROVEEDOR_TB_PK PRIMARY KEY,
TELEFONO_ID NUMBER,
NOMBRE VARCHAR2(75) CONSTRAINT FIDE_PROVEEDOR_TB_NOMBRE_NOT_NULL NOT NULL,
CONTACTO VARCHAR2(100),
DIRECCION VARCHAR2(100),
EMAIL VARCHAR2(75) CONSTRAINT FIDE_PROVEEDOR_TB_EMAIL_NOT_NULL NOT NULL,
CONSTRAINT FIDE_PROVEEDOR_TB_FK FOREIGN KEY (TELEFONO_ID) REFERENCES FIDE_TELEFONO_TB(TELEFONO_ID)
);


----TABLA HOTEL-----.
CREATE TABLE FIDE_HOTEL_TB(
HOTEL_ID NUMBER CONSTRAINT FIDE_HOTEL_TB_PK PRIMARY KEY,
TELEFONO_ID NUMBER,
EMAIL VARCHAR2(75) CONSTRAINT FIDE_HOTEL_TB_EMAIL_UNIQUE UNIQUE,
NOMBRE VARCHAR2(100) CONSTRAINT FIDE_HOTEL_TB_NOMBRE_NOT_NULL NOT NULL,
UBICACION VARCHAR2(100),
CONSTRAINT FIDE_HOTEL_TB_ID_FK_TELEFONO FOREIGN KEY (TELEFONO_ID) REFERENCES FIDE_TELEFONO_TB(TELEFONO_ID)
);

---TABLA RESTAURANTE---
CREATE TABLE FIDE_RESTAURANTE_TB(
RESTAURANTE_ID NUMBER CONSTRAINT FIDE_RESTAURANTE_TB_PK PRIMARY KEY,
HOTEL_ID NUMBER,
NOMBRE VARCHAR2(100) CONSTRAINT FIDE_RESTAURANTE_TB_NOMBRE_NOT_NULL NOT NULL,
CAPACIDAD NUMBER,
ESTILO VARCHAR2(100),
CONSTRAINT FIDE_RESTAURANTE_TB_FK FOREIGN KEY (HOTEL_ID) REFERENCES FIDE_HOTEL_TB(HOTEL_ID)
);
--- TABLA HUESPED----

CREATE TABLE FIDE_HUESPED_TB(
HUESPED_ID NUMBER CONSTRAINT FIDE_HUESPED_TB_PK PRIMARY KEY,
TELEFONO_ID NUMBER,
NOMBRE VARCHAR2(100) CONSTRAINT FIDE_HUESPED_TB_NOMBRE_NOT_NULL NOT NULL,
APELLIDO1 VARCHAR2(100),
APELLIDO2 VARCHAR2(100),
EMAIL VARCHAR2(75) CONSTRAINT FIDE_HUESPED_TB_EMAIL_UNIQUE UNIQUE,
DIRECCION VARCHAR2(100),
FECHA_REGISTRO DATE,
CONSTRAINT FIDE_HUESPED_TB_FK FOREIGN KEY (TELEFONO_ID) REFERENCES FIDE_TELEFONO_TB(TELEFONO_ID)
);

---TABLA TIPO DE HABITACION---

CREATE TABLE FIDE_TIPO_HABITACION_TB (
TIPO_HABITACION_ID NUMBER CONSTRAINT FIDE_TIPO_HABITACION_TB_PK PRIMARY KEY,
VISTA VARCHAR2(50),
CAMAS NUMBER,
AMENIDADES VARCHAR2(200)
);

--- HABITACION----
CREATE TABLE FIDE_HABITACION_TB (
    HABITACION_ID NUMBER CONSTRAINT FIDE_HABITACION_TB_PK PRIMARY KEY,
    HOTEL_ID NUMBER,
    TIPO_HABITACION_ID NUMBER,
    HUESPED_ID NUMBER,
    ESTADO VARCHAR2(50),
    NUMERO VARCHAR2(10),
    CONSTRAINT FIDE_HABITACION_TB_HOTEL_ID_FK FOREIGN KEY (HOTEL_ID) REFERENCES FIDE_HOTEL_TB(HOTEL_ID),
    CONSTRAINT FIDE_HABITACION_TB_TIPO_HABITACION_FK FOREIGN KEY (TIPO_HABITACION_ID) REFERENCES FIDE_TIPO_HABITACION_TB(TIPO_HABITACION_ID),
    CONSTRAINT FIDE_HABITACION_TB_HUESPED_FK FOREIGN KEY (HUESPED_ID) REFERENCES FIDE_HUESPED_TB(HUESPED_ID)
);

---TABLA-MANTENIMIENTO

CREATE TABLE FIDE_MANTENIMIENTO_TB (
MANTENIMIENTO_ID NUMBER CONSTRAINT FIDE_MANTENIMIENTO_TB_PK PRIMARY KEY,
HOTEL_ID NUMBER,
HABITACION_ID NUMBER,
AREA_COMUN VARCHAR2(50),
FECHA_MANTENIMIENTO DATE CONSTRAINT FIDE_MANTENIMIENTO_TB_FECHA_NOT_NULL NOT NULL,
DESCRIPCION VARCHAR2(200),
ESTADO VARCHAR2(50) NOT NULL,
CONSTRAINT FIDE_MANTENIMIENTO_TB_HOTEL_ID_FK FOREIGN KEY (HOTEL_ID) REFERENCES FIDE_HOTEL_TB(HOTEL_ID),
CONSTRAINT FIDE_MANTENIMIENTO_TB_HABITACION_ID_FK FOREIGN KEY (HABITACION_ID) REFERENCES FIDE_HABITACION_TB(HABITACION_ID)
);

---Tabla incidente

CREATE TABLE FIDE_INCIDENTE_TB(
INCIDENTE_ID NUMBER CONSTRAINT FIDE_INCIDENTE_TB_PK PRIMARY KEY,
HUESPED_ID NUMBER,
HABITACION_ID NUMBER,
FECHA_INCIDENTE DATE CONSTRAINT FIDE_INCIDENTE_TB_FECHA_NOT_NULL NOT NULL,
DESCRIPCION VARCHAR2(200),
ESTADO VARCHAR2(50),
CONSTRAINT FIDE_INCIDENTE_TB_HUESPED_ID_FK FOREIGN KEY (HUESPED_ID) REFERENCES FIDE_HUESPED_TB(HUESPED_ID),
CONSTRAINT FIDE_INCIDENTE_TB_HABITACION_ID_FK FOREIGN KEY (HABITACION_ID) REFERENCES FIDE_HABITACION_TB (HABITACION_ID)
);

-----CATEOGRIA DE SUMINISTROS-----

CREATE TABLE FIDE_CATEGORIA_SUMINISTRO_TB (
CATEGORIA_ID NUMBER CONSTRAINT FIDE_CATEGORIA_SUMINISTRO_TB_PK PRIMARY KEY,
NOMBRE VARCHAR2(100) CONSTRAINT FIDE_CATEGORIA_SUMINISTRO_TB_NOMBRE_NOT_NULL NOT NULL,
DESCRIPCION VARCHAR2(200)
);

---- SUMINISTROS
CREATE TABLE FIDE_SUMINISTRO_TB (
SUMINISTRO_ID NUMBER CONSTRAINT FIDE_SUMINISTRO_TB_PK PRIMARY KEY,
CATEGORIA_ID NUMBER,
PROVEEDOR_ID NUMBER,
CANTIDAD NUMBER,
PRECIO_UNITARIO NUMBER(10,2) CONSTRAINT FIDE_SUMINISTRO_TB_PRECIO_NOT_NULL NOT NULL,
CONSTRAINT FIDE_SUMINISTRO_TB_CATEGORIA_ID_FK FOREIGN KEY (CATEGORIA_ID) REFERENCES FIDE_CATEGORIA_SUMINISTRO_TB(CATEGORIA_ID),
CONSTRAINT FIDE_SUMINISTRO_TB_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID) REFERENCES FIDE_PROVEEDOR_TB(PROVEEDOR_ID)
);

----INVENTARIO--------
CREATE TABLE FIDE_INVENTARIO_TB(
INVENTARIO_ID NUMBER CONSTRAINT FIDE_INVENTARIO_TB_PK PRIMARY KEY,
HOTEL_ID NUMBER,
SUMINISTRO_ID NUMBER,
CANTIDAD_DISPONIBLE NUMBER,
CONSTRAINT FIDE_INVENTARIO_TB_HOTEL_ID_FK FOREIGN KEY (HOTEL_ID) REFERENCES FIDE_HOTEL_TB(HOTEL_ID),
CONSTRAINT FIDE_INVENTARIO_TB_SUMINISTRO_ID_FK FOREIGN KEY (SUMINISTRO_ID) REFERENCES FIDE_SUMINISTRO_TB(SUMINISTRO_ID)
);

---SERVICIO ADICCIONAL---
CREATE TABLE FIDE_SERVICIO_ADICIONAL_TB (
SERVICIO_ID NUMBER CONSTRAINT FIDE_SERVICIO_ADICIONAL_TB_PK PRIMARY KEY,
NOMBRE VARCHAR2(100) CONSTRAINT FIDE_SERVICIO_ADICIONAL_TB_NOMBRE_NOT_NULL NOT NULL,
DESCRIPCION VARCHAR2(200),
PRECIO NUMBER(10,2) NOT NULL
);

---RESERVACION----

CREATE TABLE FIDE_RESERVACION_TB(
RESERVACION_ID NUMBER CONSTRAINT FIDE_RESERVACION_TB_PK PRIMARY KEY,
HOTEL_ID NUMBER,
HUESPED_ID NUMBER,
HABITACION_ID NUMBER,
ESTADO VARCHAR2(50),
FECHA_RESERVACION DATE CONSTRAINT FIDE_RESERVACION_TB_FECHA_NOT_NULL NOT NULL,
CONSTRAINT FIDE_RESERVACION_TB_HOTEL_ID_FK FOREIGN KEY(HOTEL_ID) REFERENCES FIDE_HOTEL_TB(HOTEL_ID),
CONSTRAINT FIDE_RESERVACION_TB_HUESPED_ID_FK FOREIGN KEY(HUESPED_ID) REFERENCES FIDE_HUESPED_TB(HUESPED_ID),
CONSTRAINT FIDE_RESERVACION_TB_HABITACION_ID_FK FOREIGN KEY(HABITACION_ID) REFERENCES FIDE_HABITACION_TB(HABITACION_ID)
)
---- FIDE_RESERVACION_SERVICIO_TB
CREATE TABLE FIDE_RESERVACION_SERVICIO_TB(
RESERVACION_SERVICIO_ID NUMBER CONSTRAINT FIDE_RESERVACION_SERVICIO_TB_PK PRIMARY KEY,
RESERVACION_ID NUMBER,
SERVICIO_ID NUMBER,
CONSTRAINT FIDE_RESERVACION_SERVICIO_TB_RESERVACION_ID_FK FOREIGN KEY(RESERVACION_ID) REFERENCES FIDE_RESERVACION_TB(RESERVACION_ID),
CONSTRAINT FIDE_RESERVACION_SERVICIO_TB_SERVICIO_ID_FK FOREIGN KEY(SERVICIO_ID) REFERENCES FIDE_SERVICIO_ADICIONAL_TB(SERVICIO_ID)
);

--- RESERVACION DE RESTAURANTE---
CREATE TABLE FIDE_RESERVACION_RESTAURANTE_TB(
RESERVACION_RESTAURANTE_ID NUMBER CONSTRAINT FIDE_RESERVACION_RESTAURANTE_TB_PK PRIMARY KEY,
RESTAURANTE_ID NUMBER,
RESERVACION_ID NUMBER,
FECHA DATE CONSTRAINT FIDE_RESERVACION_RESTAURANTE_TB_FECHA_NOT_NULL NOT NULL,
ESTADO VARCHAR2(50),
CONSTRAINT FIDE_RESERVACION_RESTAURANTE_TB_RESTAURANTE_ID_FK FOREIGN KEY(RESTAURANTE_ID) REFERENCES FIDE_RESTAURANTE_TB(RESTAURANTE_ID),
CONSTRAINT FIDE_RESERVACION_RESTAURANTE_TB_RESERVACION_ID_FK FOREIGN KEY(RESERVACION_ID) REFERENCES FIDE_RESERVACION_TB(RESERVACION_ID)
);
---- METODO DE PAGO---
CREATE TABLE FIDE_METODO_PAGO_TB(
METODO_PAGO_ID NUMBER CONSTRAINT FIDE_METODO_PAGO_TB_PK PRIMARY KEY,
NOMBRE VARCHAR2(100) CONSTRAINT  FIDE_METODO_PAGO_TB_NOMBRE_NOT_NULL NOT NULL
);
----TABLA PROMOCION---
CREATE TABLE FIDE_PROMOCION_TB (
PROMOCION_ID NUMBER CONSTRAINT FIDE_PROMOCION_TB_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(200),
DESCUENTO NUMBER(10,2) CONSTRAINT FIDE_PROMOCION_TB_DESCUENTO_NOT_NULL NOT NULL,
FECHA_INICIO DATE CONSTRAINT FIDE_PROMOCION_TB_FECHA_INICIO_NOT_NULL NOT NULL,
FECHA_FIN DATE CONSTRAINT FIDE_PROMOCION_TB_FECHA_FIN_NOT_NULL NOT NULL
);

----PROMOCIONA APLICADA
CREATE TABLE FIDE_PROMOCION_APLICADA_TB(
PROMOCION_APLICADA_ID NUMBER CONSTRAINT FIDE_PROMOCION_APLICADA_TB_PK PRIMARY KEY,
PROMOCION_ID NUMBER,
RESERVACION_ID NUMBER,
FECHA_APLICACION DATE CONSTRAINT FIDE_PROMOCION_APLICADA_TB_FECHA_APLICACION_NOT_NULL NOT NULL,
CONSTRAINT FIDE_PROMOCION_APLICADA_TB_PROMOCION_ID_FK FOREIGN KEY (PROMOCION_ID) REFERENCES FIDE_PROMOCION_TB(PROMOCION_ID),
CONSTRAINT FIDE_PROMOCION_APLICADA_TB_RESERVA_ID_FK FOREIGN KEY (RESERVACION_ID) REFERENCES FIDE_RESERVACION_TB(RESERVACION_ID)
);
---TABLA PAGO------

CREATE TABLE FIDE_PAGO_TB (
PAGO_ID NUMBER CONSTRAINT FIDE_PAGO_TB_PK PRIMARY KEY,
RESERVACION_ID NUMBER,
METODO_PAGO_ID NUMBER,
PROMOCION_APLICADA_ID NUMBER,
MONTO NUMBER(10,2) CONSTRAINT FIDE_PAGO_TB_MONTO_NOT_NULL NOT NULL,
ESTADO VARCHAR2(50),
CONSTRAINT FIDE_PAGO_TB_RESERVACION_ID_FK FOREIGN KEY (RESERVACION_ID) REFERENCES FIDE_RESERVACION_TB(RESERVACION_ID),
CONSTRAINT FIDE_PAGO_TB_METODO_PAGO_ID_FK FOREIGN KEY (METODO_PAGO_ID) REFERENCES FIDE_METODO_PAGO_TB(METODO_PAGO_ID),
CONSTRAINT FIDE_PAGO_TB_PROMOCION_APLICADA_ID_FK FOREIGN KEY (PROMOCION_APLICADA_ID) REFERENCES FIDE_PROMOCION_APLICADA_TB(PROMOCION_APLICADA_ID)
);

COMMIT;
